apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kaniko
      image: 'gcr.io/kaniko-project/executor:v1.9.1-debug'
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 500Mi
          cpu: 200m
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      configMap:
        name: docker-config

