apiVersion: v1
kind: Pod
spec:
  containers:
    - name: hello-php
      image: 'php:8.1.11-alpine'
      command:
        - tail
        - '-f'
        - /dev/null
      tty: true
      imagePullPolicy: Always
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 100Mi
    - name: kaniko
      image: 'gcr.io/kaniko-project/executor:v1.9.1-debug'
      imagePullPolicy: Always
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 500Mi
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      configMap:
        name: docker-config

